### ISSUE TITLE
Add support for locale generation using claude AI

### ISSUE THREAD

**Issue by westoque** [narralabs/i18n-ai#2]

**Comment by wilburhimself** [comment]
Hi @westoque This is a really nice gem idea, I will surely use it a lot. 
I gave it a shot at adding Claude support  in #5 

Can you take a look and let me know your thoughts?

**Comment by westoque** [comment]
@wilburhimself oh. i should have put my comment on the proposed settings strategy here. but here's a link:

https://github.com/narralabs/i18n-ai/pull/5#issuecomment-2263384028
