### ISSUE TITLE
Support for local LLM ?

### ISSUE THREAD

**Issue by anthony-robin** [narralabs/i18n-ai#7]
Do you have any plan to support local running models ? (for example ollama exposes an OpenAI compatible API and allows to switch easily between local models).

For privacy reasons, it might be preferable to do translations locally instead of sending them to external remote companies when possible.

Thank you for building this great gem :)

**Comment by westoque** [comment]
thank you ❤️ 

yes. local llms will definitely be supported and is in the roadmap. there is a pending change that should make it easy to support it in the future:

https://github.com/narralabs/i18n-ai/pull/5#issuecomment-2263384028
